"""criar_tabela_armarios

Revision ID: ee3f5ba7e730
Revises: 60947615444b
Create Date: 2026-08-10 18:32:55.530366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee3f5ba7e730'
down_revision: Union[str, Sequence[str], None] = '60947615444b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('localizacao', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('aluno_nome', sa.String(length=150), nullable=True),
    sa.Column('turma', sa.String(length=100), nullable=True),
    sa.Column('contato', sa.String(length=100), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_termino', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_armarios_id'), 'armarios', ['id'], unique=False)
    op.create_index(op.f('ix_armarios_numero'), 'armarios', ['numero'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_armarios_numero'), table_name='armarios')
    op.drop_index(op.f('ix_armarios_id'), table_name='armarios')
    op.drop_table('armarios')
    # ### end Alembic commands ###
